version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
    - 9.8.6
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: chalk
    versions:
    - 4.1.0
  - dependency-name: gulp-postcss
    versions:
    - 8.0.0
  - dependency-name: postcss-simple-vars
    versions:
    - 5.0.2
